#+TITLE: ~/ Anurag Peshne
#+OPTIONS: toc:nil num:nil creator:t author:nil timestamp:nil
#+INCLUDE: "../assets/commonHead.org"
#+INCLUDE: "../assets/ga.org"
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="./gameoflife/gol.css">
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="css/style.css" />
#+HTML_HEAD: <script src="./gameoflife/gol.js"></script>
#+EXPORT_OPTIONS: comments:t
#+AUTHOR: Anurag Peshne

#+BEGIN_export html
<script type="text/javascript">
window.onload = function() {
    var contentWidth = document.getElementById("content").offsetWidth;
    var gol_container = document.getElementById("gameoflife_container");
    gol_container.style.height = "300px";
    var delay = 2000;
    var preset = "random";
    var game = new GameOfLife(gol_container, preset)
    game.play(delay);
};
</script>
<a href="./gameoflife/index.html"><div id="gameoflife_container"></div></a>
#+END_export
* Hello
  My name is Anurag Peshne. I'm interested in Programing Languages, Distributed
  Systems, Text Editors (particularly Vim and Emacs), Lisp and Functional
  Programing.

  I'm a software engineer at Microsoft; I studied Computer Science at [[http://www.ufl.edu/][University of Florida]]
  and [[http://vnit.ac.in/][VNIT]] and have experience working with server teams at multinational corporations
  as well as a startup.

  Besides computer related stuff, I'm interested in cycling and [[https://www.flickr.com/photos/anuragpeshne/][photography]]. Moon and time lapsed
  photography are my favorites. Here's my [[./now.org][/now]] page: the things I'm upto these days.

  If you haven't already recognized the animation above, it's [[./gameoflife/index.html][Conway's Game of Life]].

* Projects
  Here are some of my somewhat working projects:
  - [[https://github.com/anuragpeshne/dsplotty][dsplotty]]
    Grid visualizer originally made for virtualizing /gossip protocol/ using websockets.
  - [[https://github.com/anuragpeshne/portal][Portal]]
    Peer to Peer file transfer using Browsers - Winner of SwampHacks Hackathon.
  - [[https://github.com/anuragpeshne/vKeyboard][vKeyboard]]
   Share keyboard accoss computers over the network.
  - [[https://github.com/anuragpeshne/austerity][austerity]]
   Bunch of shell scripts to restrict access to time /wasting/ websites.
  - [[https://github.com/anuragpeshne/font8x8][font8X8]]
   Language agnostic monochrome bitmap font for rendering.
  - [[https://github.com/anuragpeshne/airLift][airLift]]
   Automated file sharing over network.
  - [[https://github.com/anuragpeshne/funJmp][funJmp]]
   Jump to function definition in Vim using Regex.
  - [[https://github.com/anuragpeshne][github.com/anuragpeshne]]
   Rest of the projects can be found at my github repo.

* Essays
  - [[file:./essays/energy-monitoring.html][Energy Monitoring using Smart plug and Raspberry Pi]]
  - [[file:./essays/understanding-genserver.html][Understanding ~GenServer~]]
  - [[file:./essays/vim/1.org][Vim Tutorials]]
  - [[file:./essays/gitTutorial.org][Git Tutorial]]
  - [[file:./essays/permissions101.org][Unix Permissions 101]]
  - [[file:./essays/keywords.org][Keywords]]
  - [[file:./essays/emacsSpeed.org][Speeding Up Emacs]]
  - [[file:./essays/asynchronous.org][Asynchronous]]
  - [[https://github.com/anuragpeshne/Y-Combinator/blob/master/Ycombinator.org][Y Combinator]]
  - [[file:./essays/index.org][/essays]] Rest of the essays

* Notes
  Bunch of notes from me, to me.
  - [[file:./notes/dns.org][How DNS work]]
  - [[file:./notes/elixir.org][Elixir Lang]]
  - [[file:./notes/data-structures/tree.org][data-structures/tree]]
  - [[file:./notes/plp.org][Programming Language Principles]]
  - [[file:./notes/concurrentProg.org][Concurrent Programming]]
  - [[file:./notes/computerNetwork.org][Computer Networks]]
* Contact
  Feel free to drop me a mail at [[mailto:anurag.peshne@gmail.com][anurag.peshne@gmail.com]], find me on [[https://www.linkedin.com/in/anuragpeshne][Linkedin]],
  [[https://github.com/anuragpeshne/][Github]] or browse my [[https://www.flickr.com/photos/anuragpeshne/][photostream]].

  [[file:./anurag.pub][Here's]] my public PGP
#+BEGIN_SRC PGP_key_fingerprint
E060 17E9 0ABB B748 2099  C617 78BD 84D1 BA5D E5
#+END_SRC
